### ISSUE TITLE
Only works for pip 8.0.0 and 8.0.1

### ISSUE THREAD

**Issue by ghost** [bartTC/pip-check#2]
Default pip version for Ubuntu (1.5.6) displays:

```
Traceback (most recent call last):
File "pip-check", line 28, in <module>
    for package, update, source in package_list:
File "/mnt/terabyte/development/pip-check/compat/list.py", line 14, in find_packages_latest_versions
    for dist in get_installed_distributions(
NameError: global name 'get_installed_distributions' is not defined
```

pip version 6.0.0 onwards display:

```
Loading packages....Traceback (most recent call last):
    File "pip-check", line 76, in <module>
        table_data[i].append([colored_label, 'Version', 'Latest']),
IndexError: list index out of range
```

Only versions 8.0.0 and 8.0.1 work without error.

**Comment by bartTC** [comment]
Thank you. In investigated this and its a bit strange. I created a tox file to check a range of versions and 7.x fails indeed. while a manual install works fine.

```
(pipcheck) 🌀  ~/Workspace/pip-check master?$ pip install -U pip==7.0
You are using pip version 7.1.0, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip==7.0
  Downloading pip-7.0.0-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 457kB/s
Installing collected packages: pip
  Found existing installation: pip 7.1.0
    Uninstalling pip-7.1.0:
      Successfully uninstalled pip-7.1.0
Successfully installed pip-7.0.0
(pipcheck) 🌀  ~/Workspace/pip-check master?$ python ./pip-check
Loading packages......................
┌────────────────────┬─────────┬────────┬───────────────────────────────────────────────┐
│ Unchanged Packages │ Version │ Latest │                                               │
├────────────────────┼─────────┼────────┼───────────────────────────────────────────────┤
│ appnope            │ 0.1.0   │ 0.1.0  │ https://pypi.python.org/pypi/appnope          │
│ colorama           │ 0.3.6   │ 0.3.6  │ https://pypi.python.org/pypi/colorama         │
│ colorclass         │ 1.2.0   │ 1.2.0  │ https://pypi.python.org/pypi/colorclass       │
│ decorator          │ 4.0.6   │ 4.0.6  │ https://pypi.python.org/pypi/decorator        │
│ fish               │ 1.1     │ 1.1    │ https://pypi.python.org/pypi/fish             │
│ gnureadline        │ 6.3.3   │ 6.3.3  │ https://pypi.python.org/pypi/gnureadline      │
│ ipdb               │ 0.8.1   │ 0.8.1  │ https://pypi.python.org/pypi/ipdb             │
│ ipython-genutils   │ 0.1.0   │ 0.1.0  │ https://pypi.python.org/pypi/ipython-genutils │
│ path.py            │ 8.1.2   │ 8.1.2  │ https://pypi.python.org/pypi/path.py          │
│ pexpect            │ 4.0.1   │ 4.0.1  │ https://pypi.python.org/pypi/pexpect          │
│ pickleshare        │ 0.6     │ 0.6    │ https://pypi.python.org/pypi/pickleshare      │
│ ptyprocess         │ 0.5.1   │ 0.5.1  │ https://pypi.python.org/pypi/ptyprocess       │
│ simplegeneric      │ 0.8.1   │ 0.8.1  │ https://pypi.python.org/pypi/simplegeneric    │
│ termcolor          │ 1.1.0   │ 1.1.0  │ https://pypi.python.org/pypi/termcolor        │
│ terminaltables     │ 2.1.0   │ 2.1.0  │ https://pypi.python.org/pypi/terminaltables   │
│ traitlets          │ 4.1.0   │ 4.1.0  │ https://pypi.python.org/pypi/traitlets        │
└────────────────────┴─────────┴────────┴───────────────────────────────────────────────┘

┌──────────────────────┬─────────┬────────┬─────────────────────────────────────────┐
│ Minor Release Update │ Version │ Latest │                                         │
├──────────────────────┼─────────┼────────┼─────────────────────────────────────────┤
│ Django               │ 1.3     │ 1.9.2  │ https://pypi.python.org/pypi/Django     │
│ ipython              │ 4.0.3   │ 4.1.1  │ https://pypi.python.org/pypi/ipython    │
│ setuptools           │ 19.6.2  │ 19.7   │ https://pypi.python.org/pypi/setuptools │
│ wheel                │ 0.26.0  │ 0.29.0 │ https://pypi.python.org/pypi/wheel      │
└──────────────────────┴─────────┴────────┴─────────────────────────────────────────┘

┌──────────────────────┬─────────┬────────┬───────────────────────────────────────┐
│ Major Release Update │ Version │ Latest │                                       │
├──────────────────────┼─────────┼────────┼───────────────────────────────────────┤
│ pip                  │ 7.0.0   │ 8.0.2  │ https://pypi.python.org/pypi/pip      │
│ Pygments             │ 1.0     │ 2.1    │ https://pypi.python.org/pypi/Pygments │
└──────────────────────┴─────────┴────────┴───────────────────────────────────────┘``

**Comment by bartTC** [comment]
This was actually just python, it works down to pip 6. 

```
py27-pip-6 runtests: commands[0] | pip-check
Loading packages......
┌──────────────────────┬─────────┬────────┬──────────────────────────────────┐
│ Major Release Update │ Version │ Latest │                                  │
├──────────────────────┼─────────┼────────┼──────────────────────────────────┤
│ pip                  │ 6.1.1   │ 8.0.2  │ https://pypi.python.org/pypi/pip │
└──────────────────────┴─────────┴────────┴──────────────────────────────────┘
```
