### ISSUE TITLE
Add Python 3.10 support

### ISSUE THREAD

**Issue by nikolaevaxenov** [bartTC/pip-check#32]
Please add support of new version on Python. When I type `pip-check` this happens

```
# pip-check
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\pip-check.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\pip_check\__init__.py", line 48, in <module>
    import colorclass
  File "C:\Python310\lib\site-packages\colorclass\__init__.py", line 11, in <module>
    from colorclass.codes import list_tags  # noqa
  File "C:\Python310\lib\site-packages\colorclass\codes.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Python310\lib\collections\__init__.py)
```

**Comment by XVilka** [comment]
@bartTC could you please publish a new release as well?

**Comment by bartTC** [comment]
Yes, `pip-check==2.7` is on pypi and you should have no problems with Python 3.10. Otherwise please reopen the ticket.
