### ISSUE TITLE
TypeError with `pyglet==2.0.dev23`

### ISSUE THREAD

**Issue by KyleKing** [bartTC/pip-check#34]
I am running into an issue with the latest version of `pip-check`

```sh
> pip install pyglet==2.0.dev23 pip-check
> pip-check
Loading package versions...
Traceback (most recent call last):
  File "~/test-project/.venv/bin/pip-check", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x10e85fbe0>
    └ <module 'sys' (built-in)>
  File "~/test-project/.venv/lib/python3.10/site-packages/pip_check/__init__.py", line 298, in main
    if current > latest:
  File "~/test-project/.venv/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 84, in __gt__
    c = self._cmp(other)
        │         └ LooseVersion ('2.0.0')
        └ LooseVersion ('2.0.dev23')
  File "~/test-project/.venv/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 352, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by KyleKing** [comment]
Maybe the `TypeError` could be suppressed and in the catch, there could be a string-wise comparison?

https://github.com/bartTC/pip-check/blob/d5ded8c2100ceecf5425ee8e3480d6809d5420c0/src/pip_check/__init__.py#L292-L298

**Comment by bartTC** [comment]
Hrm, coul dyou tell me your exact Python, pip and setuptools version? I didn't have a problem with stock Python 3.10.

```
Loading package versions...

┌──────────────────────┬─────────────┬────────┬─────────────────────────────────────────┐
│ Major Release Update │ Version     │ Latest │                                         │
├──────────────────────┼─────────────┼────────┼─────────────────────────────────────────┤
│ Django               │ 1.10        │ 4.1.3  │ https://pypi.python.org/pypi/Django     │
│ html5lib             │ 0.999999999 │ 1.1    │ https://pypi.python.org/pypi/html5lib   │
│ pyglet               │ 2.0.dev23   │ 2.0.0  │ https://pypi.python.org/pypi/pyglet     │
│ setuptools           │ 65.3.0      │ 65.5.1 │ https://pypi.python.org/pypi/setuptools │
│ wheel                │ 0.37.1      │ 0.38.2 │ https://pypi.python.org/pypi/wheel      │
└──────────────────────┴─────────────┴────────┴─────────────────────────────────────────┘```

**Comment by KyleKing** [comment]
Thanks for the quick reply! I quickly tried setuptools `65.3.0` along with pip `21.3.1`, but I have a feeling it might have to do with poetry and distutils

```sh
> poetry new test-dir
> cd test-dir
> poetry add pyglet==2.0.dev23 pip-check==2.7
> poetry shell
> python --version
Python 3.10.5
> pip --version
pip 22.3.1
> pip show setuptools
Version: 65.5.1
> python -m pip freeze
pip-check==2.7
pyglet==2.0.dev23
terminaltables==3.1.10
> pip-check
(error)
```

**Comment by KyleKing** [comment]
But when I use the latest from `main`, `pip-check` works, so I think this can be closed pending the next release where packaging replaces distutils

```sh
> poetry add git+https://github.com/bartTC/pip-check.git@main
> poetry run pip-check --cmd="poetry run pip"
Loading package versions...

┌──────────────────────┬───────────┬────────┬─────────────────────────────────────────┐
│ Major Release Update │ Version   │ Latest │                                         │
├──────────────────────┼───────────┼────────┼─────────────────────────────────────────┤
│ pip                  │ 22.3      │ 22.3.1 │ https://pypi.python.org/pypi/pip        │
│ pyglet               │ 2.0.dev23 │ 2.0.0  │ https://pypi.python.org/pypi/pyglet     │
│ setuptools           │ 65.5.0    │ 65.5.1 │ https://pypi.python.org/pypi/setuptools │
│ wheel                │ 0.37.1    │ 0.38.2 │ https://pypi.python.org/pypi/wheel      │
└──────────────────────┴───────────┴────────┴─────────────────────────────────────────┘

┌────────────────────┬─────────┬────────┬─────────────────────────────────────────────┐
│ Unchanged Packages │ Version │ Latest │                                             │
├────────────────────┼─────────┼────────┼─────────────────────────────────────────────┤
│ packaging          │ 21.3    │ 21.3   │ https://pypi.python.org/pypi/packaging      │
│ pyparsing          │ 3.0.9   │ 3.0.9  │ https://pypi.python.org/pypi/pyparsing      │
│ terminaltables     │ 3.1.10  │ 3.1.10 │ https://pypi.python.org/pypi/terminaltables │
└────────────────────┴─────────┴────────┴─────────────────────────────────────────────┘
```

**Comment by bartTC** [comment]
Doh, I never made a release with that. There's now pip-check==2.8 which should solve your issue.
